file=open('/file handling/practice session 20/example.txt', "w")
file.write('first instruction\n')
file.write('2nd instruction\n')
file.write('3rd instruction\n')
file.write('4th instruction\n')
file.close()
print('completed')